### ISSUE TITLE
Python Port

### ISSUE THREAD

**Issue by MaartenGr** [zfedoran/pixel-sprite-generator#7]
Hi,

I created a basic python port for the project and was wondering whether you would add it to your list of ports: https://github.com/MaartenGr/Sprite-Generator. 

It is highly appreciated!

**Comment by zfedoran** [comment]
Hi @MaartenGr, no problem! I've added it with 9532396e7b8c917e50c12d2b2ae0437037f6f704

I'm excited to see a python port! Thanks!
